services:
  postgres:
    image: pgvector/pgvector:pg18
    container_name: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"

  postgresml:
    image: ghcr.io/postgresml/postgresml:2.10.0
    container_name: postgresml
    restart: unless-stopped
    ports:
      - "5433:5432"
      - "8000:8000"
    volumes:
      - postgresml_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgresml -d postgresml"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  postgresml_data:
